---
# tasks file for roles/pihole_dns
- name: Create a DNS in a file
  ansible.builtin.template:
    src: pihole-dns.j2
    dest: /etc/pihole/custom.list
    mode: '0644'
  when: pihole_dns is defined
  notify: FTL Restart

- name: Create a CNAME in a file
  ansible.builtin.template:
    src: pihole-cname.j2
    dest: /etc/dnsmasq.d/05-pihole-custom-cname.conf
    mode: '0644'
  when: pihole_cname is defined
  notify: FTL Restart